# -*- coding: utf-8 -*-
"""ai_resume_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jtc9USWlZuQ4uxzVAUV9eo_ZkNPhPm6m
"""

# ----------------------------------------------------------
# AI RESUME ANALYZER WITH SIMPLE RAG (NO FAISS VERSION)
# ----------------------------------------------------------

# Install required package if missing:
# pip install sentence-transformers

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# ----------------------------------------------------------
# 1. Load Mini Embedding Model
# ----------------------------------------------------------

model = SentenceTransformer("all-MiniLM-L6-v2")

# ----------------------------------------------------------
# 2. Create knowledge base (RAG Documents)
# ----------------------------------------------------------

knowledge_base = [
    "Add measurable achievements like percentages or numbers.",
    "Include technical skills relevant to the job description.",
    "Use action verbs like developed, implemented, designed, built.",
    "Keep resume to one or two pages maximum.",
    "Add project links to GitHub or portfolio.",
    "Mention internships, certifications, and relevant coursework.",
    "Include ML, AI, and RAG projects clearly under Projects section.",
    "Avoid long paragraphs; use short bullet points.",
    "Add keywords from the job description for ATS optimization.",
    "Include a summary section highlighting strengths."
]

# Embed knowledge base sentences
kb_embeddings = model.encode(knowledge_base)

# ----------------------------------------------------------
# 3. Take user's resume text
# ----------------------------------------------------------

print("--------------------------------------------------")
print("        AI RESUME ANALYZER WITH RAG")
print("--------------------------------------------------")
print("Paste your resume text below (small or big):")
print("When finished, type ### on a new line and press Enter.")

resume_lines = []
while True:
    line = input()
    if line.strip() == "###":
        break
    resume_lines.append(line)

resume_text = " ".join(resume_lines)

# ----------------------------------------------------------
# 4. Convert resume to embedding
# ----------------------------------------------------------

resume_embedding = model.encode([resume_text])

# ----------------------------------------------------------
# 5. Compute similarity between resume and each tip
# ----------------------------------------------------------

similarities = cosine_similarity(resume_embedding, kb_embeddings)[0]

# Get top 3 relevant suggestions
top_indices = similarities.argsort()[::-1][:3]

# ----------------------------------------------------------
# 6. Print suggestions
# ----------------------------------------------------------

print("\n--------------------------------------------------")
print("       AI RAG-BASED RESUME IMPROVEMENTS")
print("--------------------------------------------------")

for i, idx in enumerate(top_indices):
    print(f"{i+1}. {knowledge_base[idx]}")

print("\n--------------------------------------------------")
print("      Analysis Complete. Good luck! 🚀")
print("--------------------------------------------------")